# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        MainWindow.setMaximumSize(QtCore.QSize(870, 550))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("QMainWindow{background-color:blue ;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heaterLabelMode = QtWidgets.QToolButton(self.centralwidget)
        self.heaterLabelMode.setGeometry(QtCore.QRect(510, 170, 101, 41))
        self.heaterLabelMode.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
" QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.heaterLabelMode.setText("")
        self.heaterLabelMode.setIconSize(QtCore.QSize(42, 42))
        self.heaterLabelMode.setObjectName("heaterLabelMode")
        self.timerButton = QtWidgets.QToolButton(self.centralwidget)
        self.timerButton.setGeometry(QtCore.QRect(670, 170, 101, 41))
        self.timerButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
" QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/play_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timerButton.setIcon(icon)
        self.timerButton.setIconSize(QtCore.QSize(42, 42))
        self.timerButton.setObjectName("timerButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 366, 801, 1))
        self.line.setStyleSheet("Line{\n"
"\n"
" \n"
"    border-width: 1px;\n"
" \n"
"    border-color: beige; \n"
"  \n"
" \n"
"    background-color:#aa0000;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.muteToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.muteToolButton.setGeometry(QtCore.QRect(540, 270, 72, 61))
        self.muteToolButton.setMinimumSize(QtCore.QSize(72, 61))
        self.muteToolButton.setMaximumSize(QtCore.QSize(72, 61))
        self.muteToolButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/speaker-on-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muteToolButton.setIcon(icon1)
        self.muteToolButton.setIconSize(QtCore.QSize(42, 42))
        self.muteToolButton.setObjectName("muteToolButton")
        self.setPointBtn = QtWidgets.QToolButton(self.centralwidget)
        self.setPointBtn.setGeometry(QtCore.QRect(440, 270, 72, 61))
        self.setPointBtn.setMinimumSize(QtCore.QSize(72, 61))
        self.setPointBtn.setMaximumSize(QtCore.QSize(72, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setPointBtn.setFont(font)
        self.setPointBtn.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"     font: bold 18px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;;\n"
"    border-style: inset;\n"
"}")
        self.setPointBtn.setIconSize(QtCore.QSize(42, 42))
        self.setPointBtn.setObjectName("setPointBtn")
        self.unitChangeToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.unitChangeToolButton.setGeometry(QtCore.QRect(630, 270, 72, 61))
        self.unitChangeToolButton.setMinimumSize(QtCore.QSize(72, 61))
        self.unitChangeToolButton.setMaximumSize(QtCore.QSize(72, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.unitChangeToolButton.setFont(font)
        self.unitChangeToolButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 24px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.unitChangeToolButton.setIconSize(QtCore.QSize(42, 42))
        self.unitChangeToolButton.setObjectName("unitChangeToolButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(540, 40, 60, 60))
        self.label_10.setMinimumSize(QtCore.QSize(60, 60))
        self.label_10.setMaximumSize(QtCore.QSize(60, 60))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../../.designer/backup/icon/heater_white_60_60.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 60, 60))
        self.label_9.setMinimumSize(QtCore.QSize(60, 60))
        self.label_9.setMaximumSize(QtCore.QSize(60, 60))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("icon/thermometer_60_60.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.tempLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel4.setGeometry(QtCore.QRect(100, 150, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.tempLabel4.setFont(font)
        self.tempLabel4.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempLabel4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tempLabel4.setObjectName("tempLabel4")
        self.setLabelAirTemp = QtWidgets.QLabel(self.centralwidget)
        self.setLabelAirTemp.setGeometry(QtCore.QRect(350, 170, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.setLabelAirTemp.setFont(font)
        self.setLabelAirTemp.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setLabelAirTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.setLabelAirTemp.setObjectName("setLabelAirTemp")
        self.setTitleLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel4.setGeometry(QtCore.QRect(160, 130, 51, 20))
        self.setTitleLabel4.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel4.setFont(font)
        self.setTitleLabel4.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.setTitleLabel4.setObjectName("setTitleLabel4")
        self.setTitleLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel2.setGeometry(QtCore.QRect(360, 130, 61, 20))
        self.setTitleLabel2.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel2.setFont(font)
        self.setTitleLabel2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.setTitleLabel2.setObjectName("setTitleLabel2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 60, 60))
        self.label_8.setMinimumSize(QtCore.QSize(60, 60))
        self.label_8.setMaximumSize(QtCore.QSize(60, 60))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("icon/thermometer_60_60.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.setTitleLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel1.setGeometry(QtCore.QRect(350, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel1.setFont(font)
        self.setTitleLabel1.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.setTitleLabel1.setObjectName("setTitleLabel1")
        self.setTitleLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel3.setGeometry(QtCore.QRect(150, 10, 61, 20))
        self.setTitleLabel3.setMaximumSize(QtCore.QSize(160, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel3.setFont(font)
        self.setTitleLabel3.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.setTitleLabel3.setObjectName("setTitleLabel3")
        self.tempLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel3.setGeometry(QtCore.QRect(90, 40, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.tempLabel3.setFont(font)
        self.tempLabel3.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel3.setObjectName("tempLabel3")
        self.setLabelSkinTemp = QtWidgets.QLabel(self.centralwidget)
        self.setLabelSkinTemp.setGeometry(QtCore.QRect(340, 60, 101, 40))
        self.setLabelSkinTemp.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.setLabelSkinTemp.setFont(font)
        self.setLabelSkinTemp.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setLabelSkinTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.setLabelSkinTemp.setObjectName("setLabelSkinTemp")
        self.setTitleLabel2_2 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel2_2.setGeometry(QtCore.QRect(510, 140, 91, 20))
        self.setTitleLabel2_2.setMaximumSize(QtCore.QSize(160, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel2_2.setFont(font)
        self.setTitleLabel2_2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.setTitleLabel2_2.setObjectName("setTitleLabel2_2")
        self.setTitleLabel4_2 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel4_2.setGeometry(QtCore.QRect(480, 20, 160, 20))
        self.setTitleLabel4_2.setMaximumSize(QtCore.QSize(160, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel4_2.setFont(font)
        self.setTitleLabel4_2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.setTitleLabel4_2.setWordWrap(True)
        self.setTitleLabel4_2.setObjectName("setTitleLabel4_2")
        self.heaterLabelShow = QtWidgets.QLabel(self.centralwidget)
        self.heaterLabelShow.setGeometry(QtCore.QRect(500, 60, 81, 40))
        self.heaterLabelShow.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.heaterLabelShow.setFont(font)
        self.heaterLabelShow.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.heaterLabelShow.setAlignment(QtCore.Qt.AlignCenter)
        self.heaterLabelShow.setObjectName("heaterLabelShow")
        self.patientDetailsToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.patientDetailsToolButton.setGeometry(QtCore.QRect(320, 270, 72, 61))
        self.patientDetailsToolButton.setMinimumSize(QtCore.QSize(72, 61))
        self.patientDetailsToolButton.setMaximumSize(QtCore.QSize(72, 61))
        self.patientDetailsToolButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.patientDetailsToolButton.setIconSize(QtCore.QSize(42, 42))
        self.patientDetailsToolButton.setObjectName("patientDetailsToolButton")
        self.setTitleLabel2_4 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel2_4.setGeometry(QtCore.QRect(10, 290, 100, 40))
        self.setTitleLabel2_4.setMinimumSize(QtCore.QSize(100, 40))
        self.setTitleLabel2_4.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel2_4.setFont(font)
        self.setTitleLabel2_4.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel2_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.setTitleLabel2_4.setObjectName("setTitleLabel2_4")
        self.patientIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.patientIdLineEdit.setGeometry(QtCore.QRect(150, 300, 150, 31))
        self.patientIdLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.patientIdLineEdit.setMaximumSize(QtCore.QSize(150, 40))
        self.patientIdLineEdit.setObjectName("patientIdLineEdit")
        self.patientNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.patientNameLineEdit.setGeometry(QtCore.QRect(150, 260, 150, 31))
        self.patientNameLineEdit.setMaximumSize(QtCore.QSize(150, 40))
        self.patientNameLineEdit.setObjectName("patientNameLineEdit")
        self.setTitleLabel2_3 = QtWidgets.QLabel(self.centralwidget)
        self.setTitleLabel2_3.setGeometry(QtCore.QRect(10, 250, 131, 40))
        self.setTitleLabel2_3.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.setTitleLabel2_3.setFont(font)
        self.setTitleLabel2_3.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.setTitleLabel2_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.setTitleLabel2_3.setObjectName("setTitleLabel2_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 380, 100, 20))
        self.label_7.setMinimumSize(QtCore.QSize(100, 20))
        self.label_7.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.timerShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.timerShowLabel.setGeometry(QtCore.QRect(650, 70, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.timerShowLabel.setFont(font)
        self.timerShowLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.timerShowLabel.setMidLineWidth(100)
        self.timerShowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerShowLabel.setObjectName("timerShowLabel")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(670, 20, 100, 20))
        self.label_11.setMinimumSize(QtCore.QSize(100, 20))
        self.label_11.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(706, 400, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/SST.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.skinTempUnit = QtWidgets.QLabel(self.centralwidget)
        self.skinTempUnit.setGeometry(QtCore.QRect(270, 60, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.skinTempUnit.setFont(font)
        self.skinTempUnit.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}")
        self.skinTempUnit.setScaledContents(True)
        self.skinTempUnit.setObjectName("skinTempUnit")
        self.airTempUnit = QtWidgets.QLabel(self.centralwidget)
        self.airTempUnit.setGeometry(QtCore.QRect(270, 170, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.airTempUnit.setFont(font)
        self.airTempUnit.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}")
        self.airTempUnit.setScaledContents(True)
        self.airTempUnit.setObjectName("airTempUnit")
        self.probeLabel = QtWidgets.QLabel(self.centralwidget)
        self.probeLabel.setGeometry(QtCore.QRect(14, 412, 73, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.probeLabel.setFont(font)
        self.probeLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.probeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.probeLabel.setObjectName("probeLabel")
        self.probeIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.probeIconLabel.setGeometry(QtCore.QRect(14, 438, 80, 25))
        self.probeIconLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.probeIconLabel.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.probeIconLabel.setText("")
        self.probeIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.probeIconLabel.setObjectName("probeIconLabel")
        self.fanFailLabel = QtWidgets.QLabel(self.centralwidget)
        self.fanFailLabel.setGeometry(QtCore.QRect(610, 412, 52, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fanFailLabel.setFont(font)
        self.fanFailLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fanFailLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.fanFailLabel.setScaledContents(False)
        self.fanFailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fanFailLabel.setObjectName("fanFailLabel")
        self.fanFailIcon = QtWidgets.QLabel(self.centralwidget)
        self.fanFailIcon.setGeometry(QtCore.QRect(600, 438, 80, 25))
        self.fanFailIcon.setMinimumSize(QtCore.QSize(80, 25))
        self.fanFailIcon.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.fanFailIcon.setText("")
        self.fanFailIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.fanFailIcon.setObjectName("fanFailIcon")
        self.tempHighLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempHighLabel.setGeometry(QtCore.QRect(110, 412, 74, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tempHighLabel.setFont(font)
        self.tempHighLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempHighLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempHighLabel.setObjectName("tempHighLabel")
        self.tempHighIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempHighIconLabel.setGeometry(QtCore.QRect(112, 438, 80, 25))
        self.tempHighIconLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.tempHighIconLabel.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempHighIconLabel.setText("")
        self.tempHighIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempHighIconLabel.setObjectName("tempHighIconLabel")
        self.heaterLabelFail = QtWidgets.QLabel(self.centralwidget)
        self.heaterLabelFail.setGeometry(QtCore.QRect(307, 412, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.heaterLabelFail.setFont(font)
        self.heaterLabelFail.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.heaterLabelFail.setAlignment(QtCore.Qt.AlignCenter)
        self.heaterLabelFail.setObjectName("heaterLabelFail")
        self.heaterIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.heaterIconLabel.setGeometry(QtCore.QRect(307, 438, 80, 25))
        self.heaterIconLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.heaterIconLabel.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.heaterIconLabel.setText("")
        self.heaterIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.heaterIconLabel.setObjectName("heaterIconLabel")
        self.powerLabelFail = QtWidgets.QLabel(self.centralwidget)
        self.powerLabelFail.setGeometry(QtCore.QRect(405, 412, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.powerLabelFail.setFont(font)
        self.powerLabelFail.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.powerLabelFail.setAlignment(QtCore.Qt.AlignCenter)
        self.powerLabelFail.setObjectName("powerLabelFail")
        self.powerIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.powerIconLabel.setGeometry(QtCore.QRect(405, 438, 80, 25))
        self.powerIconLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.powerIconLabel.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.powerIconLabel.setText("")
        self.powerIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.powerIconLabel.setObjectName("powerIconLabel")
        self.systemLabelFail = QtWidgets.QLabel(self.centralwidget)
        self.systemLabelFail.setGeometry(QtCore.QRect(503, 412, 84, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.systemLabelFail.setFont(font)
        self.systemLabelFail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.systemLabelFail.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.systemLabelFail.setScaledContents(False)
        self.systemLabelFail.setAlignment(QtCore.Qt.AlignCenter)
        self.systemLabelFail.setObjectName("systemLabelFail")
        self.systemIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.systemIconLabel.setGeometry(QtCore.QRect(503, 438, 80, 25))
        self.systemIconLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.systemIconLabel.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.systemIconLabel.setText("")
        self.systemIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.systemIconLabel.setObjectName("systemIconLabel")
        self.tempLowIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempLowIconLabel.setGeometry(QtCore.QRect(209, 438, 80, 25))
        self.tempLowIconLabel.setMinimumSize(QtCore.QSize(80, 25))
        self.tempLowIconLabel.setStyleSheet("QLabel{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempLowIconLabel.setText("")
        self.tempLowIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLowIconLabel.setObjectName("tempLowIconLabel")
        self.tempLowLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempLowLabel.setGeometry(QtCore.QRect(210, 412, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tempLowLabel.setFont(font)
        self.tempLowLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempLowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLowLabel.setObjectName("tempLowLabel")
        self.openSettingDialog = QtWidgets.QToolButton(self.centralwidget)
        self.openSettingDialog.setGeometry(QtCore.QRect(720, 270, 72, 61))
        self.openSettingDialog.setMinimumSize(QtCore.QSize(72, 61))
        self.openSettingDialog.setMaximumSize(QtCore.QSize(72, 61))
        self.openSettingDialog.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00FF00 ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;;\n"
"    border-style: inset;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/settings_white_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openSettingDialog.setIcon(icon2)
        self.openSettingDialog.setIconSize(QtCore.QSize(42, 42))
        self.openSettingDialog.setObjectName("openSettingDialog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.patientIdLineEdit, self.patientDetailsToolButton)
        MainWindow.setTabOrder(self.patientDetailsToolButton, self.setPointBtn)
        MainWindow.setTabOrder(self.setPointBtn, self.muteToolButton)
        MainWindow.setTabOrder(self.muteToolButton, self.unitChangeToolButton)
        MainWindow.setTabOrder(self.unitChangeToolButton, self.timerButton)
        MainWindow.setTabOrder(self.timerButton, self.heaterLabelMode)
        MainWindow.setTabOrder(self.heaterLabelMode, self.patientNameLineEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timerButton.setText(_translate("MainWindow", "Start"))
        self.muteToolButton.setText(_translate("MainWindow", "MUTE"))
        self.setPointBtn.setText(_translate("MainWindow", "SET"))
        self.unitChangeToolButton.setText(_translate("MainWindow", "°F"))
        self.tempLabel4.setText(_translate("MainWindow", "36.6"))
        self.setLabelAirTemp.setText(_translate("MainWindow", "36.6"))
        self.setTitleLabel4.setText(_translate("MainWindow", "AIR"))
        self.setTitleLabel2.setText(_translate("MainWindow", "SET"))
        self.setTitleLabel1.setText(_translate("MainWindow", "SET"))
        self.setTitleLabel3.setText(_translate("MainWindow", "SKIN"))
        self.tempLabel3.setText(_translate("MainWindow", "36.6"))
        self.setLabelSkinTemp.setText(_translate("MainWindow", "36.6"))
        self.setTitleLabel2_2.setText(_translate("MainWindow", "MODE"))
        self.setTitleLabel4_2.setText(_translate("MainWindow", "HEATER POWER"))
        self.heaterLabelShow.setText(_translate("MainWindow", "100"))
        self.patientDetailsToolButton.setText(_translate("MainWindow", "Patient \n"
"Details"))
        self.setTitleLabel2_4.setText(_translate("MainWindow", "Patient ID:"))
        self.setTitleLabel2_3.setText(_translate("MainWindow", "Patient Name:"))
        self.label_7.setText(_translate("MainWindow", "Alarms"))
        self.timerShowLabel.setText(_translate("MainWindow", "00"))
        self.label_11.setText(_translate("MainWindow", "TIMER"))
        self.label_2.setText(_translate("MainWindow", "%"))
        self.skinTempUnit.setText(_translate("MainWindow", "°C"))
        self.airTempUnit.setText(_translate("MainWindow", "°C"))
        self.probeLabel.setText(_translate("MainWindow", "Probe Fail"))
        self.fanFailLabel.setText(_translate("MainWindow", "Fan Fail"))
        self.tempHighLabel.setText(_translate("MainWindow", "Skin Hi/Lo"))
        self.heaterLabelFail.setText(_translate("MainWindow", "Heater Fail"))
        self.powerLabelFail.setText(_translate("MainWindow", "Heater On"))
        self.systemLabelFail.setText(_translate("MainWindow", "System Fail"))
        self.tempLowLabel.setText(_translate("MainWindow", "Air Hi/Lo"))
        self.openSettingDialog.setText(_translate("MainWindow", "SET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
