# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patientDetailsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_patientFormWindow(object):
    def setupUi(self, patientFormWindow):
        patientFormWindow.setObjectName("patientFormWindow")
        patientFormWindow.resize(800, 480)
        patientFormWindow.setMinimumSize(QtCore.QSize(800, 480))
        patientFormWindow.setMaximumSize(QtCore.QSize(800, 480))
        patientFormWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        patientFormWindow.setStyleSheet("QMainWindow{background-color:blue ;}")
        self.centralwidget = QtWidgets.QWidget(patientFormWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 4, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.saveToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.saveToolButton.setGeometry(QtCore.QRect(373, 244, 72, 72))
        self.saveToolButton.setMinimumSize(QtCore.QSize(72, 72))
        self.saveToolButton.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.saveToolButton.setFont(font)
        self.saveToolButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 18px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed { \n"
"    background-color:#535353;\n"
"    border-style: inset;\n"
"}")
        self.saveToolButton.setObjectName("saveToolButton")
        self.cancelToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.cancelToolButton.setGeometry(QtCore.QRect(463, 244, 72, 72))
        self.cancelToolButton.setMinimumSize(QtCore.QSize(72, 72))
        self.cancelToolButton.setMaximumSize(QtCore.QSize(72, 72))
        self.cancelToolButton.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 18px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: #535353;\n"
"    border-style: inset;\n"
"}")
        self.cancelToolButton.setObjectName("cancelToolButton")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(310, 48, 300, 40))
        self.nameLineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(124, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(124, 150, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.ageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ageLineEdit.setGeometry(QtCore.QRect(310, 94, 300, 40))
        self.ageLineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.ageLineEdit.setObjectName("ageLineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(124, 200, 171, 19))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(124, 60, 180, 19))
        self.label.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.label.setObjectName("label")
        self.patientIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.patientIdLineEdit.setGeometry(QtCore.QRect(310, 186, 300, 40))
        self.patientIdLineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.patientIdLineEdit.setObjectName("patientIdLineEdit")
        self.sexLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sexLineEdit.setGeometry(QtCore.QRect(310, 140, 300, 40))
        self.sexLineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.sexLineEdit.setObjectName("sexLineEdit")
        patientFormWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(patientFormWindow)
        QtCore.QMetaObject.connectSlotsByName(patientFormWindow)
        patientFormWindow.setTabOrder(self.patientIdLineEdit, self.saveToolButton)
        patientFormWindow.setTabOrder(self.saveToolButton, self.cancelToolButton)
        patientFormWindow.setTabOrder(self.cancelToolButton, self.nameLineEdit)
        patientFormWindow.setTabOrder(self.nameLineEdit, self.ageLineEdit)
        patientFormWindow.setTabOrder(self.ageLineEdit, self.sexLineEdit)

    def retranslateUi(self, patientFormWindow):
        _translate = QtCore.QCoreApplication.translate
        patientFormWindow.setWindowTitle(_translate("patientFormWindow", "Patient Details Form"))
        self.label_5.setText(_translate("patientFormWindow", "Patient Details"))
        self.saveToolButton.setText(_translate("patientFormWindow", "Save"))
        self.cancelToolButton.setText(_translate("patientFormWindow", "Close"))
        self.label_2.setText(_translate("patientFormWindow", "Age:"))
        self.label_3.setText(_translate("patientFormWindow", "Sex:"))
        self.label_4.setText(_translate("patientFormWindow", "Patient Id:"))
        self.label.setText(_translate("patientFormWindow", "Patient Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    patientFormWindow = QtWidgets.QMainWindow()
    ui = Ui_patientFormWindow()
    ui.setupUi(patientFormWindow)
    patientFormWindow.show()
    sys.exit(app.exec_())
