# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'servoManualSetPointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_servoManualSetPointForm(object):
    def setupUi(self, servoManualSetPointForm):
        servoManualSetPointForm.setObjectName("servoManualSetPointForm")
        servoManualSetPointForm.resize(800, 480)
        servoManualSetPointForm.setMinimumSize(QtCore.QSize(800, 480))
        servoManualSetPointForm.setMaximumSize(QtCore.QSize(800, 480))
        servoManualSetPointForm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        servoManualSetPointForm.setStyleSheet("QMainWindow{background-color:blue ;}")
        self.centralwidget = QtWidgets.QWidget(servoManualSetPointForm)
        self.centralwidget.setObjectName("centralwidget")
        self.okHeaterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.okHeaterBtn.setGeometry(QtCore.QRect(310, 306, 100, 40))
        self.okHeaterBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.okHeaterBtn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.okHeaterBtn.setFont(font)
        self.okHeaterBtn.setObjectName("okHeaterBtn")
        self.heaterUpToolBtn = QtWidgets.QToolButton(self.centralwidget)
        self.heaterUpToolBtn.setGeometry(QtCore.QRect(490, 130, 72, 72))
        self.heaterUpToolBtn.setMinimumSize(QtCore.QSize(72, 72))
        self.heaterUpToolBtn.setMaximumSize(QtCore.QSize(72, 72))
        self.heaterUpToolBtn.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF ;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/plus-sign-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.heaterUpToolBtn.setIcon(icon)
        self.heaterUpToolBtn.setIconSize(QtCore.QSize(42, 40))
        self.heaterUpToolBtn.setObjectName("heaterUpToolBtn")
        self.heaterDownToolBtn = QtWidgets.QToolButton(self.centralwidget)
        self.heaterDownToolBtn.setGeometry(QtCore.QRect(280, 130, 72, 72))
        self.heaterDownToolBtn.setMinimumSize(QtCore.QSize(72, 72))
        self.heaterDownToolBtn.setMaximumSize(QtCore.QSize(72, 72))
        self.heaterDownToolBtn.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/minus_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.heaterDownToolBtn.setIcon(icon1)
        self.heaterDownToolBtn.setIconSize(QtCore.QSize(42, 42))
        self.heaterDownToolBtn.setObjectName("heaterDownToolBtn")
        self.cancelHeaterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelHeaterBtn.setGeometry(QtCore.QRect(420, 306, 100, 40))
        self.cancelHeaterBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.cancelHeaterBtn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cancelHeaterBtn.setFont(font)
        self.cancelHeaterBtn.setObjectName("cancelHeaterBtn")
        self.heaterOutput = QtWidgets.QLabel(self.centralwidget)
        self.heaterOutput.setGeometry(QtCore.QRect(360, 150, 120, 40))
        self.heaterOutput.setMinimumSize(QtCore.QSize(120, 40))
        self.heaterOutput.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.heaterOutput.setFont(font)
        self.heaterOutput.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.heaterOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.heaterOutput.setObjectName("heaterOutput")
        self.skinTextLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.skinTextLabel_2.setGeometry(QtCore.QRect(310, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.skinTextLabel_2.setFont(font)
        self.skinTextLabel_2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.skinTextLabel_2.setObjectName("skinTextLabel_2")
        servoManualSetPointForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(servoManualSetPointForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        servoManualSetPointForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(servoManualSetPointForm)
        self.statusbar.setObjectName("statusbar")
        servoManualSetPointForm.setStatusBar(self.statusbar)

        self.retranslateUi(servoManualSetPointForm)
        QtCore.QMetaObject.connectSlotsByName(servoManualSetPointForm)

    def retranslateUi(self, servoManualSetPointForm):
        _translate = QtCore.QCoreApplication.translate
        servoManualSetPointForm.setWindowTitle(_translate("servoManualSetPointForm", "Set Point"))
        self.okHeaterBtn.setText(_translate("servoManualSetPointForm", "Ok"))
        self.heaterUpToolBtn.setText(_translate("servoManualSetPointForm", "..."))
        self.heaterDownToolBtn.setText(_translate("servoManualSetPointForm", "..."))
        self.cancelHeaterBtn.setText(_translate("servoManualSetPointForm", "Cancel"))
        self.heaterOutput.setText(_translate("servoManualSetPointForm", "100"))
        self.skinTextLabel_2.setText(_translate("servoManualSetPointForm", "Set Heater Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    servoManualSetPointForm = QtWidgets.QMainWindow()
    ui = Ui_servoManualSetPointForm()
    ui.setupUi(servoManualSetPointForm)
    servoManualSetPointForm.show()
    sys.exit(app.exec_())
