# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setPointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 300)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("QDialog{background-color:blue ;}")
        self.tempDownToolBtn2 = QtWidgets.QToolButton(Dialog)
        self.tempDownToolBtn2.setGeometry(QtCore.QRect(130, 120, 72, 72))
        self.tempDownToolBtn2.setMinimumSize(QtCore.QSize(72, 72))
        self.tempDownToolBtn2.setMaximumSize(QtCore.QSize(72, 72))
        self.tempDownToolBtn2.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/minus_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tempDownToolBtn2.setIcon(icon)
        self.tempDownToolBtn2.setIconSize(QtCore.QSize(42, 42))
        self.tempDownToolBtn2.setObjectName("tempDownToolBtn2")
        self.tempUpToolBtn2 = QtWidgets.QToolButton(Dialog)
        self.tempUpToolBtn2.setGeometry(QtCore.QRect(340, 120, 72, 72))
        self.tempUpToolBtn2.setMinimumSize(QtCore.QSize(72, 72))
        self.tempUpToolBtn2.setMaximumSize(QtCore.QSize(72, 72))
        self.tempUpToolBtn2.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/plus-sign-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tempUpToolBtn2.setIcon(icon1)
        self.tempUpToolBtn2.setIconSize(QtCore.QSize(42, 42))
        self.tempUpToolBtn2.setObjectName("tempUpToolBtn2")
        self.tempDownToolBtn1 = QtWidgets.QToolButton(Dialog)
        self.tempDownToolBtn1.setGeometry(QtCore.QRect(130, 20, 72, 72))
        self.tempDownToolBtn1.setMinimumSize(QtCore.QSize(72, 72))
        self.tempDownToolBtn1.setMaximumSize(QtCore.QSize(72, 72))
        self.tempDownToolBtn1.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempDownToolBtn1.setIcon(icon)
        self.tempDownToolBtn1.setIconSize(QtCore.QSize(42, 42))
        self.tempDownToolBtn1.setObjectName("tempDownToolBtn1")
        self.tempUpToolBtn1 = QtWidgets.QToolButton(Dialog)
        self.tempUpToolBtn1.setGeometry(QtCore.QRect(340, 20, 72, 72))
        self.tempUpToolBtn1.setMinimumSize(QtCore.QSize(72, 72))
        self.tempUpToolBtn1.setMaximumSize(QtCore.QSize(72, 72))
        self.tempUpToolBtn1.setStyleSheet("QToolButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
" \n"
"    padding: 6px;\n"
"    background-color: #00A36C ;\n"
"    color:#FFFFFF ;\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempUpToolBtn1.setIcon(icon1)
        self.tempUpToolBtn1.setIconSize(QtCore.QSize(42, 40))
        self.tempUpToolBtn1.setObjectName("tempUpToolBtn1")
        self.tempLabel1 = QtWidgets.QLabel(Dialog)
        self.tempLabel1.setGeometry(QtCore.QRect(210, 40, 120, 40))
        self.tempLabel1.setMinimumSize(QtCore.QSize(120, 40))
        self.tempLabel1.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.tempLabel1.setFont(font)
        self.tempLabel1.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel1.setObjectName("tempLabel1")
        self.tempLabel2 = QtWidgets.QLabel(Dialog)
        self.tempLabel2.setGeometry(QtCore.QRect(210, 140, 120, 40))
        self.tempLabel2.setMinimumSize(QtCore.QSize(120, 40))
        self.tempLabel2.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.tempLabel2.setFont(font)
        self.tempLabel2.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.tempLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel2.setObjectName("tempLabel2")
        self.okBtn = QtWidgets.QPushButton(Dialog)
        self.okBtn.setGeometry(QtCore.QRect(180, 226, 100, 40))
        self.okBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.okBtn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(290, 226, 100, 40))
        self.cancelBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.cancelBtn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.skinTextLabel = QtWidgets.QLabel(Dialog)
        self.skinTextLabel.setGeometry(QtCore.QRect(30, 50, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.skinTextLabel.setFont(font)
        self.skinTextLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.skinTextLabel.setObjectName("skinTextLabel")
        self.airTextLabel = QtWidgets.QLabel(Dialog)
        self.airTextLabel.setGeometry(QtCore.QRect(30, 160, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.airTextLabel.setFont(font)
        self.airTextLabel.setStyleSheet("QLabel{\n"
"  \n"
"    color:#FFFFFF;\n"
"}\n"
"QLabel:pressed {\n"
"    background-color: gray;\n"
"    border-style: inset;\n"
"}")
        self.airTextLabel.setObjectName("airTextLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set Point"))
        self.tempDownToolBtn2.setText(_translate("Dialog", "..."))
        self.tempUpToolBtn2.setText(_translate("Dialog", "..."))
        self.tempDownToolBtn1.setText(_translate("Dialog", "..."))
        self.tempUpToolBtn1.setText(_translate("Dialog", "..."))
        self.tempLabel1.setText(_translate("Dialog", "32"))
        self.tempLabel2.setText(_translate("Dialog", "30"))
        self.okBtn.setText(_translate("Dialog", "Ok"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
        self.skinTextLabel.setText(_translate("Dialog", "Skin Temp:"))
        self.airTextLabel.setText(_translate("Dialog", "Air Temp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
